'use client'

import React, { createContext, useContext, useEffect, useState } from 'react'

type Language = 'ar' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  dir: 'rtl' | 'ltr'
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    'login.title': 'منصة الإدارة',
    'login.subtitle': 'سجل دخولك للوصول إلى لوحة التحكم',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.remember': 'تذكرني دائماً',
    'login.submit': 'دخول للنظام',
    'login.name': 'الاسم',
    'login.secure': 'نظام مشفر بالكامل',
    'login.footer': 'جميع الحقوق محفوظة. يتم مراقبة جميع عمليات الدخول لضمان أمان النظام.',
    'nav.store': 'المتجر',
    'nav.dashboard': 'لوحة البيانات',
    'nav.orders': 'الطلبات',
    'nav.secretaries': 'السكرتاريا',
    'nav.ui_settings': 'تخصيص الواجهة',
    'nav.profile': 'إعدادات الحساب',
    'nav.products': 'المنتجات',
    'nav.home': 'الرئيسية',
    'nav.secretary_panel': 'لوحة السكرتير',
    'nav.logout': 'خروج',
    'common.save': 'حفظ التغييرات',
    'common.cancel': 'إلغاء',
    'common.add': 'إضافة',
    'common.delete': 'حذف',
    'common.search': 'بحث...',
    'common.loading': 'جاري التحميل...',
    'common.total': 'إجمالي',
    'common.logout': 'تسجيل الخروج',
    'common.confirm_logout': 'هل تريد تسجيل الخروج؟',
    'common.currency': 'ج.م',
    'common.confirm_action': 'هل أنت متأكد من هذا الإجراء؟',
    'common.success': 'تمت العملية بنجاح',
    'common.error': 'حدث خطأ ما، يرجى المحاولة لاحقاً',
    'common.error_unauthorized': 'غير مصرح لك بدخول هذه الصفحة',
    'common.author_credit': 'بواسطة محمد رضا هلهل',
    'secretary.welcome': 'أهلاً بك',
    'secretary.recent_orders': 'أحدث الطلبات المسجلة',
    'secretary.pending_orders': 'لديك اليوم {count} طلبات قيد الانتظار',
    'secretary.delivered_stat': 'طلبات تم تسليمها',
    'order.add_new': 'إضافة أوردر جديد',
    'order.customer_name': 'اسم العميل',
    'order.mobile': 'رقم الهاتف',
    'order.governorate': 'المحافظة',
    'order.address': 'المركز',
    'order.product_name': 'اسم المنتج',
    'order.select_product': '--- اختر المنتج ---',
    'order.quantity': 'الكمية',
    'order.total_amount': 'المبلغ الإجمالي',
    'order.submit': 'حفظ',
    'order.confirm_add_new_msg': 'هل أنت متأكد من إضافة أوردر جديد؟',
    'order.success': 'تم إضافة الطلب بنجاح',
    'order.error': 'فشل في إضافة الطلب',
    'order.status_shipped': 'تم الشحن',
    'order.status_pending_admin': 'بانتظار تأكيد الإدارة',
    'order.status_delivered': 'تم التسليم ✓',
    'order.status_returned': 'مرتجع',
    'order.status_not_delivered': 'لم يتم التسليم',
    'order.confirm_delivery': 'تأكيد التسليم',
    'order.confirm_return': 'تأكيد الارتجاع',
    'order.confirm_not_delivered': 'تأكيد عدم التسليم',
    'order.error_select_product': 'يرجى اختيار المنتج',
    'order.no_orders': 'لا توجد طلبات لعرضها حالياً',
    'order.waiting_admin': 'بانتظار تأكيد الإدارة',
    'order.cancelled_label': 'تم الإلغاء',
    'order.mark_returned': 'مرتجع',
    'order.contents': 'محتويات الطلب',
    'order.shipping_data': 'بيانات الشحن',
    'order.payment_verification': 'التحقق من الدفع',
    'order.full_payment': 'دفع كامل المبلغ',
    'order.deposit_payment': 'دفع العربون',
    'order.view_receipt': 'عرض إيصال العربون',
    'order.notes': 'ملاحظات الطلب',
    'order.notes_placeholder': 'أي ملاحظات إضافية (اختياري)...',
    'admin.sec_subtitle': 'إدارة حسابات السكرتاريا ومتابعة الأداء',
    'admin.sec_add_new': 'إضافة سكرتير جديد',
    'admin.sec_success_add': 'تم إضافة السكرتير بنجاح',
    'admin.sec_salary_calc': 'حساب الرواتب',
    'admin.sec_salary_hint': 'سعر القطعة * عدد الطلبات المسلمة',
    'admin.sec_piece_price': 'سعر القطعة',
    'admin.sec_salary': 'المستحق',
    'admin.sec_online': 'متصل الآن',
    'admin.sec_offline': 'غير متصل',
    'admin.sec_reset_one': 'تصفية العداد',
    'admin.sec_confirm_reset': 'هل أنت متأكد من تصفية العدادات؟',
    'admin.products_add_new': 'إضافة منتج جديد',
    'admin.products_add_action': 'إضافة المنتج',
    'admin.products_empty': 'لا توجد منتجات حالياً',
    'admin.products_empty_hint': 'ابدأ بإضافة أول منتج لمتجرك',
    'admin.products_error_fields': 'يرجى إدخال الاسم والسعر',
    'admin.products_success_add': 'تمت إضافة المنتج بنجاح',
    'admin.ui_subtitle': 'تحكم في مظهر الموقع بالكامل من هنا',
    'admin.ui_default_dark': 'الوضع الليلي كوضع افتراضي',
    'admin.ui_section_content': 'محتوى الموقع الأساسي',
    'admin.ui_site_title': 'عنوان المتجر',
    'admin.ui_section_colors': 'تخصيص الألوان المتقدم',
    'admin.ui_reset_action': 'استعادة الافتراضي',
    'admin.ui_confirm_reset': 'هل أنت متأكد من استعادة الألوان الافتراضية؟',
    'admin.ui_reset_success': 'تمت استعادة الألوان الافتراضية',
    'admin.ui_color_primary': 'اللون الرئيسي',
    'admin.ui_color_navbar': 'لون الهيدر (Navbar)',
    'admin.ui_color_card': 'لون المربعات (Cards)',
    'admin.ui_color_footer': 'لون الفوتر',
    'admin.ui_color_text': 'لون النص الأساسي',
    'admin.ui_save_action': 'حفظ كافة التغييرات',
    'admin.ui_saving': 'جاري حفظ الإعدادات...',
    'admin.orders_subtitle': 'متابعة طلبات العملاء وحالات الشحن',
    'admin.dashboard_total_sales_confirm': 'هل أنت متأكد من تصفير عداد المبيعات الإجمالي؟ هذا الإجراء سيحسب المبيعات من هذه اللحظة فصاعداً.',
    'admin.dashboard_reset_success': 'تم تصفير عداد المبيعات بنجاح',
    'admin.dashboard_reset_error': 'حدث خطأ أثناء التصفير',
    'admin.dashboard_reset_title': 'تصفير عداد المبيعات',
    'admin.dashboard_returned_orders': 'الطلبات المرتجعة',
    'admin.products_delete_confirm': 'هل أنت متأكد من حذف المنتج: {name}؟',
    'admin.products_delete_success': 'تم حذف المنتج',
    'admin.products_delete_error': 'خطأ في الحذف',
    'admin.orders_status_update_confirm': 'هل أنت متأكد من تغيير حالة الطلب إلى "{status}"؟',
    'admin.orders_status_update_success': 'تم تحديث حالة الطلب',
    'admin.orders_status_update_error': 'خطأ في التحديث',
    'admin.orders_payment_update_success': 'تم تحديث حالة الدفع',
    'admin.orders_delete_confirm': 'هل أنت متأكد من حذف هذا الطلب؟',
    'admin.orders_delete_success': 'تم حذف الطلب',
    'admin.orders_copy_success': 'تم النسخ للحافظة',
    'admin.orders_all_months': 'كل الشهور',
    'admin.orders_value': 'قيمة الطلبات:',
    'admin.products_new_placeholder': 'أدخل اسم المنتج الجديد...',
    'admin.products_save_action': 'حفظ المنتج',
    'admin.products_added_title': 'المنتجات المضافة:',
    'admin.orders_search_empty': 'لا توجد طلبات مطابقة للبحث',
    'admin.orders_shipping_data': 'بيانات الشحن',
    'admin.orders_deposit_receipt': 'إيصال العربون',
    'admin.orders_view_receipt': 'عرض إيصال العربون',
    'admin.orders_no_receipt': 'لا يوجد إيصال',
    'admin.active_products': 'المنتجات النشطة',
    'admin.today_orders': 'طلبات اليوم',
    'admin.dashboard_sales_start': 'يبدأ من:',
    'admin.total_devices': 'الأجهزة النشطة',
    'admin.sec_edit': 'تعديل',
    'admin.sec_edit_title': 'تعديل السكرتير',
    'admin.sec_reset_password': 'إرسال رابط استعادة كلمة المرور',
    'admin.sec_reset_password_success': 'تم إرسال الرابط إلى البريد الإلكتروني',
    'admin.sec_update_success': 'تم تحديث بيانات السكرتير بنجاح',
    'admin.sec_calc_confirm': 'هل أنت متأكد من حساب الرواتب لجميع السكرتيرات وتحديث سعر القطعة الثابت؟',
    'admin.sec_calc_success': 'تم حساب وتحديث رواتب جميع السكرتيرات بنجاح',
    'admin.sec_piece_reset_success': 'تم إعادة ضبط سعر القطعة إلى 300 ج.م',
    'admin.sec_calc_title': 'حساب الرواتب',
    'admin.sec_calc_desc': 'حساب وتثبيت رواتب جميع السكرتيرات بناءً على سعر القطعة',
    'admin.sec_calc_action_all': 'حساب الرواتب للجميع',
    'admin.sec_piece_reset_title': 'إعادة ضبط السعر إلى 300',
    'admin.sec_monthly_salary_manual': 'الراتب الشهري (يدوي)',
    'admin.sec_due_by_piece': 'المستحق (حسب القطع)',
    'store.hero_title': 'تسوق المستقبل',
    'store.hero_subtitle': 'منتجات فاخرة تصلك حتى باب المنزل بكل حب وعناية.',
    'store.featured_products': 'المنتجات المميزة',
    'store.browse_all': 'تصفح جميع المنتجات',
    'store.add_to_cart': 'أضف للسلة',
    'store.cart_empty': 'سلة التسوق فارغة',
    'store.checkout_title': 'تأكيد الطلب',
    'store.place_order': 'أرسل الطلب الآن',
    'store.success_title': 'تم استلام طلبك!',
    'store.success_msg': 'شكراً لطلبك. سنتواصل معك قريباً لتأكيد الشحن.',
    
    // Secretary Pages (Profile, Login, Dashboard, etc.)
    'sec_profile_title': 'البيانات الشخصية',
    'sec_profile_image_only': 'يرجى اختيار صورة فقط',
    'sec_profile_image_size': 'حجم الصورة يجب أن يكون أقل من 5 ميجابايت',
    'sec_profile_image_success': 'تم رفع الصورة بنجاح! ✨',
    'sec_profile_image_error': 'حدث خطأ في رفع الصورة',
    'sec_profile_save_success': 'تم حفظ البيانات بنجاح! ✅',
    'sec_profile_save_error': 'حدث خطأ في حفظ البيانات',
    'sec_profile_name': 'الاسم الكامل',
    'sec_profile_email': 'البريد الإلكتروني',
    'sec_profile_phone': 'رقم الهاتف',
    'sec_profile_image': 'الصورة الشخصية',
    'sec_profile_uploading': 'جاري الرفع...',
    'sec_profile_change_image': 'تغيير الصورة الشخصية',
    'sec_profile_upload_image': 'رفع صورة شخصية',
    'sec_profile_save_changes': 'حفظ التغييرات',
    'sec_salary_expected': 'الراتب المتوقع',
    'sec_role': 'سكرتير',

    'sec_login_success': 'تم تسجيل الدخول بنجاح',
    'sec_login_invalid': 'بيانات الدخول غير صحيحة',
    'sec_login_error': 'حدث خطأ أثناء تسجيل الدخول',
    'sec_login_title': 'لوحة السكرتير',
    'sec_login_subtitle': 'يرجى تسجيل الدخول للمتابعة',
    'sec_login_alert_title': 'تنبيه لأغراض الأمان',
    'sec_login_alert_msg': 'يجب أن يكون لديك حساب مفعل من قبل الإدارة لتتمكن من الوصول للمنصة.',
    'sec_login_rights': 'جميع الحقوق محفوظة \u00A9',
    
    'sec_shipped_title': 'طلبات تم شحنها',
    'sec_shipped_subtitle': 'الطلبات التي تم شحنها وفي انتظار تأكيد المسؤول',
    'sec_shipped_empty': 'لا توجد طلبات تم شحنها',
    'sec_shipped_count': 'العدد:',
    'sec_shipped_waiting': 'في انتظار المسؤول',
    'sec_shipped_qty': 'الكمية:',
    
    'sec_returned_title': 'الطلبات المرتجعة',
    'sec_returned_subtitle': 'الطلبات التي تم إرجاعها الخاصه بك',
    'sec_returned_empty': 'لا توجد طلبات مرتجعة',
    
    'sec_dash_send_success': 'تم إرسال الطلب للمسؤول بنجاح',
    'sec_dash_send_deposit': 'تم إرسال الطلب للمدير (دفع العربون)',
    'sec_dash_cancelled': 'تم إلغاء الطلب',
    'sec_dash_add_another': 'إضافة طلب آخر',
    'sec_dash_confirm_add_title': 'تأكيد إضافة الطلب',
    'sec_dash_will_add': 'سيتم إضافة طلب لـ',
    'sec_dash_with_amount': 'بمبلغ',
    'sec_dash_confirm_save': 'تأكيد وحفظ الطلب',
    'sec_dash_undo_edit': 'تراجع وتعديل'
  },
  en: {
    'login.title': 'Management Portal',
    'login.subtitle': 'Sign in to access your dashboard',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.remember': 'Remember Me',
    'login.submit': 'Login to Portal',
    'login.name': 'Name',
    'login.secure': 'Fully encrypted system',
    'login.footer': 'All rights reserved. logins are monitored.',
    'nav.store': 'Store',
    'nav.dashboard': 'Dashboard',
    'nav.orders': 'Orders',
    'nav.secretaries': 'Secretaries',
    'nav.ui_settings': 'UI Settings',
    'nav.profile': 'Profile Settings',
    'nav.products': 'Products',
    'nav.home': 'Home',
    'nav.secretary_panel': 'Secretary Panel',
    'nav.logout': 'Logout',
    'common.save': 'Save Changes',
    'common.cancel': 'Cancel',
    'common.add': 'Add',
    'common.delete': 'Delete',
    'common.search': 'Search...',
    'common.loading': 'Loading...',
    'common.total': 'Total',
    'common.logout': 'Logout',
    'common.confirm_logout': 'Do you want to logout?',
    'common.currency': 'EGP',
    'common.confirm_action': 'Are you sure about this action?',
    'common.success': 'Operation completed successfully',
    'common.error': 'Something went wrong, please try again',
    'common.error_unauthorized': 'You are not authorized to view this page',
    'common.author_credit': 'By Mohamed Reda Helhel',
    'secretary.welcome': 'Welcome',
    'secretary.recent_orders': 'Recent Registered Orders',
    'secretary.pending_orders': 'You have {count} pending orders today',
    'secretary.delivered_stat': 'Delivered Orders',
    'order.add_new': 'Add New Order',
    'order.customer_name': 'Customer Name',
    'order.mobile': 'Phone Number',
    'order.governorate': 'Governorate',
    'order.address': 'Center/District',
    'order.product_name': 'Product Name',
    'order.select_product': '--- Select Product ---',
    'order.quantity': 'Quantity',
    'order.total_amount': 'Total Amount',
    'order.submit': 'Save',
    'order.confirm_add_new_msg': 'Are you sure you want to add a new order?',
    'order.success': 'Order added successfully',
    'order.error': 'Failed to add order',
    'order.status_shipped': 'Shipped',
    'order.status_pending_admin': 'Pending Admin Confirmation',
    'order.status_delivered': 'Delivered ✓',
    'order.status_returned': 'Returned',
    'order.status_not_delivered': 'Not Delivered',
    'order.confirm_delivery': 'Confirm Delivery',
    'order.confirm_return': 'Confirm Return',
    'order.confirm_not_delivered': 'Confirm Non-delivery',
    'order.error_select_product': 'Please select a product',
    'order.no_orders': 'No orders to display currently',
    'order.waiting_admin': 'Waiting for admin confirmation',
    'order.cancelled_label': 'Cancelled',
    'order.mark_returned': 'Mark Returned',
    'order.contents': 'Order Contents',
    'order.shipping_data': 'Shipping Data',
    'order.payment_verification': 'Payment Verification',
    'order.full_payment': 'Full Payment',
    'order.deposit_payment': 'Deposit Payment',
    'order.view_receipt': 'View Deposit Receipt',
    'order.notes': 'Order Notes',
    'order.notes_placeholder': 'Any additional notes (optional)...',
    'admin.sec_subtitle': 'Manage secretary accounts and monitor performance',
    'admin.sec_add_new': 'Add New Secretary',
    'admin.sec_success_add': 'Secretary added successfully',
    'admin.sec_salary_calc': 'Salary Calculator',
    'admin.sec_salary_hint': 'Piece price * Delivered orders count',
    'admin.sec_piece_price': 'Piece Price',
    'admin.sec_salary': 'Due Salary',
    'admin.sec_online': 'Online Now',
    'admin.sec_offline': 'Offline',
    'admin.sec_reset_one': 'Reset Counter',
    'admin.sec_confirm_reset': 'Are you sure you want to reset counters?',
    'admin.products_add_new': 'Add New Product',
    'admin.products_add_action': 'Add Product',
    'admin.products_empty': 'No products currently',
    'admin.products_empty_hint': 'Start adding your first product',
    'admin.products_error_fields': 'Please enter name and price',
    'admin.products_success_add': 'Product added successfully',
    'admin.ui_subtitle': 'Control the entire site appearance from here',
    'admin.ui_default_dark': 'Dark Mode as default',
    'admin.ui_section_content': 'Basic Site Content',
    'admin.ui_site_title': 'Store Title',
    'admin.ui_section_colors': 'Advanced Color Customization',
    'admin.ui_reset_action': 'Reset to Default',
    'admin.ui_confirm_reset': 'Are you sure you want to reset colors to defaults?',
    'admin.ui_reset_success': 'Default colors restored',
    'admin.ui_color_primary': 'Primary Color',
    'admin.ui_color_navbar': 'Navbar Color',
    'admin.ui_color_card': 'Card Color',
    'admin.ui_color_footer': 'Footer Color',
    'admin.ui_color_text': 'Text Color',
    'admin.ui_save_action': 'Save All Changes',
    'admin.ui_saving': 'Saving settings...',
    'admin.orders_subtitle': 'Track customer orders and shipping status',
    'admin.dashboard_total_sales_confirm': 'Are you sure you want to reset the total sales counter? This will start counting sales from this moment onwards.',
    'admin.dashboard_reset_success': 'Sales counter reset successfully',
    'admin.dashboard_reset_error': 'Error resetting counter',
    'admin.dashboard_reset_title': 'Reset Sales Counter',
    'admin.dashboard_returned_orders': 'Returned Orders',
    'admin.products_delete_confirm': 'Are you sure you want to delete product: {name}?',
    'admin.products_delete_success': 'Product deleted successfully',
    'admin.products_delete_error': 'Error deleting product',
    'admin.orders_status_update_confirm': 'Are you sure you want to change order status to "{status}"?',
    'admin.orders_status_update_success': 'Order status updated successfully',
    'admin.orders_status_update_error': 'Error updating status',
    'admin.orders_payment_update_success': 'Payment status updated successfully',
    'admin.orders_delete_confirm': 'Are you sure you want to delete this order?',
    'admin.orders_delete_success': 'Order deleted successfully',
    'admin.orders_copy_success': 'Copied to clipboard',
    'admin.orders_all_months': 'All Months',
    'admin.orders_value': 'Orders Value:',
    'admin.products_new_placeholder': 'Enter new product name...',
    'admin.products_save_action': 'Save Product',
    'admin.products_added_title': 'Added Products:',
    'admin.orders_search_empty': 'No orders matching your search',
    'admin.orders_shipping_data': 'Shipping Data',
    'admin.orders_deposit_receipt': 'Deposit Receipt',
    'admin.orders_view_receipt': 'View Deposit Receipt',
    'admin.orders_no_receipt': 'No receipt found',
    'admin.active_products': 'Active Products',
    'admin.today_orders': 'Today\'s Orders',
    'admin.dashboard_sales_start': 'Starts from:',
    'admin.total_devices': 'Active Devices',
    'admin.sec_edit': 'Edit',
    'admin.sec_edit_title': 'Edit Secretary',
    'admin.sec_reset_password': 'Send Password Reset Link',
    'admin.sec_reset_password_success': 'Password reset link sent to email',
    'admin.sec_update_success': 'Secretary data updated successfully',
    'admin.sec_calc_confirm': 'Are you sure you want to calculate salaries for all secretaries and update fixed piece price?',
    'admin.sec_calc_success': 'Salaries calculated and updated for all secretaries successfully',
    'admin.sec_piece_reset_success': 'Piece price reset to 300 EGP successfully',
    'admin.sec_calc_title': 'Salary Calculator',
    'admin.sec_calc_desc': 'Calculate and set salaries for all secretaries based on piece price',
    'admin.sec_calc_action_all': 'Calculate Salaries for All',
    'admin.sec_piece_reset_title': 'Reset price to 300',
    'admin.sec_monthly_salary_manual': 'Monthly Salary (Manual)',
    'admin.sec_due_by_piece': 'Due (By Piece)',
    'store.hero_title': 'Shop the Future',
    'store.hero_subtitle': 'Premium products delivered to your doorstep with love and care.',
    'store.featured_products': 'Featured Products',
    'store.browse_all': 'Browse All Products',
    'store.add_to_cart': 'Add to Cart',
    'store.cart_empty': 'Your cart is empty',
    'store.checkout_title': 'Complete Order',
    'store.place_order': 'Place Order Now',
    'store.success_title': 'Order Placed!',
    'store.success_msg': 'Thank you for your order. We will contact you soon.',

    // Secretary Pages (Profile, Login, Dashboard, etc.)
    'sec_profile_title': 'Personal Data',
    'sec_profile_image_only': 'Please select an image only',
    'sec_profile_image_size': 'Image size must be less than 5MB',
    'sec_profile_image_success': 'Image uploaded successfully! ✨',
    'sec_profile_image_error': 'Error uploading image',
    'sec_profile_save_success': 'Data saved successfully! ✅',
    'sec_profile_save_error': 'Error saving data',
    'sec_profile_name': 'Full Name',
    'sec_profile_email': 'Email Address',
    'sec_profile_phone': 'Phone Number',
    'sec_profile_image': 'Profile Image',
    'sec_profile_uploading': 'Uploading...',
    'sec_profile_change_image': 'Change Profile Image',
    'sec_profile_upload_image': 'Upload Profile Image',
    'sec_profile_save_changes': 'Save Changes',
    'sec_salary_expected': 'Expected Salary',
    'sec_role': 'Secretary',

    'sec_login_success': 'Logged in successfully',
    'sec_login_invalid': 'Invalid login details',
    'sec_login_error': 'Error during login',
    'sec_login_title': 'Secretary Panel',
    'sec_login_subtitle': 'Please login to continue',
    'sec_login_alert_title': 'Security Alert',
    'sec_login_alert_msg': 'You must have an activated account by the administration to access the platform.',
    'sec_login_rights': 'All rights reserved \u00A9',
    
    'sec_shipped_title': 'Shipped Orders',
    'sec_shipped_subtitle': 'Orders shipped and waiting for admin confirmation',
    'sec_shipped_empty': 'No shipped orders',
    'sec_shipped_count': 'Count:',
    'sec_shipped_waiting': 'Waiting for Admin',
    'sec_shipped_qty': 'Qty:',
    
    'sec_returned_title': 'Returned Orders',
    'sec_returned_subtitle': 'Your returned orders',
    'sec_returned_empty': 'No returned orders',
    
    'sec_dash_send_success': 'Order sent to admin successfully',
    'sec_dash_send_deposit': 'Order sent to admin (Deposit Paid)',
    'sec_dash_cancelled': 'Order Cancelled',
    'sec_dash_add_another': 'Add Another Order',
    'sec_dash_confirm_add_title': 'Confirm Add Order',
    'sec_dash_will_add': 'An order will be added for',
    'sec_dash_with_amount': 'With an amount of',
    'sec_dash_confirm_save': 'Confirm and Save Order',
    'sec_dash_undo_edit': 'Undo and Edit'
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ar')

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language
    if (saved && (saved === 'ar' || saved === 'en')) {
      setLanguageState(saved)
    }
  }, [])

  const dir = language === 'ar' ? 'rtl' : 'ltr'

  useEffect(() => {
    const root = document.documentElement
    root.setAttribute('lang', language)
    root.setAttribute('dir', dir)
  }, [language, dir])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string) => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
